package/rust-bin: fix armv7-unknown-linux-gnueabi
Commit d69d40c029dc7d8199b745eaee759d92b66c5d17 forgot to add hash for
armv7-unknown-linux-gnueabi resulting in the following build failure:

ERROR: No hash found for rust-std-1.54.0-armv7-unknown-linux-gnueabi.tar.xz

Fixes:
 - http://autobuild.buildroot.org/results/443f94bb9ae0addb5130f96fb363ec9651e8af3d

Signed-off-by: Fabrice Fontaine <fontaine.fabrice@gmail.com>
Signed-off-by: Thomas Petazzoni <thomas.petazzoni@bootlin.com>
(cherry picked from commit dd432a78867f2b88d50b2bcc465bc1c094992c26)