package/python-cbor2: enable as host python package
Zephyr build system depends on click and since it is a build it will
run the host packages.

    Traceback (most recent call last):
      File "emb-mcu-local/extern/zephyrproject/bootloader/" \
           "mcuboot/scripts/imgtool/boot_record.py", line 21, in <module>
        from cbor2 import dumps
    ModuleNotFoundError: No module named 'cbor2'

Signed-off-by: Charles Hardin <charles.hardin@chargepoint.com>