package/python-click: enable as host python package
Zephyr build system depends on click and since it is a build it will
run the host packages.

    Traceback (most recent call last):
      File "emb-mcu-local/extern/zephyrproject/bootloader/mcuboot/" \
           "scripts/imgtool.py", line 19, in <module>
        from imgtool import main
      File "emb-mcu-local/extern/zephyrproject/bootloader/mcuboot/" \
           "scripts/imgtool/main.py", line 21, in <module>
        import click
    ModuleNotFoundError: No module named 'click'

Signed-off-by: Charles Hardin <charles.hardin@chargepoint.com>